[wokwi]
elf = ".pio/build/esp32dev/firmware.elf"
firmware = ".pio/build/esp32dev/firmware.bin"
gdbServerPort = 50000

[env]
platform = "espressif32"
board = "esp32dev"
framework = "arduino"

[[net.forward]]
from = "localhost:8180"
to = "target:80"